export const branch = [
            'CSE',
            'ECE',
            'EE',
            'ME',
            'CE',
            'MCT',
            'AE',
            'BCA',
            'MCA',
            'BBA',
            'MBA',
            'B.Com',
            'B.Arch',
            'B.Des',
            'B.Pharm',
            'B.Sc Nursing',
            'BPT',
            'B.A. LL.B.',
            'JMC',
            'HM',
        ];